### ISSUE TITLE
Assets should be per wallet instead of shared per network across all wallets 

### ISSUE THREAD

**Issue by CryptoToit** [aphtoken/aph-wallet-gui#115]
Hi,

Running Wallet version 2.0.5 Logged in to my main address / account: 

When I go to Assets and select a specific Token I then click on "Remove". I get a confirmation notification that the Token is removed, but it has not been removed from the lost. Also when I go to my Dashboard it is still there. Have tried this a couple times. Also logged out and back in and tired it again, same issue. 

When I go to a different address / account the remove function works just fine. However, when I log back in all the tokens I removed is back showing again.

![screen shot 2018-08-01 at 12 40 49](https://user-images.githubusercontent.com/36384396/43518601-e9225f9c-958c-11e8-9fdc-42c7c7be3562.png)

![screen shot 2018-08-01 at 12 43 15](https://user-images.githubusercontent.com/36384396/43518609-efa3052e-958c-11e8-8ac0-36758b6df1ee.png)

**Comment by jsolman** [comment]
Do you have a balance on those tokens? We currently don't support removing tokens for which you have balance. If you want to remove the token for which you have a balance, send the balance to another wallet address and then remove.

Is the balance not showing for the token? (the white greyed area you have in the dotted square on the right)

**Comment by jsolman** [comment]
Ok, I figured this out. We had a bug where remove was sometimes being shown on assets on the dashboard. To remove tokens currently the wallet only supports this use case from the Assets page. For now, I'm fixing the bug that was showing the remove button erroneously on the Dashboard.

**Comment by jsolman** [comment]
This issue is fixed by https://github.com/aphtoken/aph-wallet-gui/commit/e7da1f87fd2498303f1b65873518f7158e5a9ed1

**Comment by jsolman** [comment]
Well, that fixes a good chunk of the problem; actually removing the assets are still delayed though, because we could be fetching assets while trying to remove the item; this ends up delaying actual removal of the item; going to reopen this open until we can try to improve the lag in removal.

**Comment by jsolman** [comment]
Actually, since the remove seems to be reliable, even though delayed, I'm going to close this.

**Comment by jsolman** [comment]
Currently your tokens are not per wallet. So opening a different wallet that has additional balances on tokens causes those tokens to get added for that network. Opening another wallet will then have those tokens added also. We need to make changes to keep tokens per wallet and per network instead of just per network.

**Comment by jsolman** [comment]
The tokens  are now stored per wallet address so this issue should now be resolved.
