### ISSUE TITLE
My interface stays blank

### ISSUE THREAD

**Issue by 100kdiamond** [aphtoken/aph-wallet-gui#18]
Hello all,
I have a mac computer with the most recent operating system.  I downloaded the wallet but I cannot get the interface to appear as shown in the Youtube video.  Can anyone please tell me what I need to do?  Thank you very much.  I am very excited for this project.  
 
[Screen Shot 2018-04-30 at 10.25.19 AM.pdf](https://github.com/aphtoken/aph-wallet-gui/files/1960953/Screen.Shot.2018-04-30.at.10.25.19.AM.pdf)

**Comment by FerrySchuller** [comment]
There is some maintenance going on on the servers, please try again later. For up to date live information you better can join the Aphelion Telegram group. https://t.me/apheliontoken

**Comment by 100kdiamond** [comment]
Thank you very much for the reply.

**Comment by jsolman** [comment]
Multiple operational improvements have been made, and server availability has improved, so I'm going to close this issue. We are still working on additional operational improvements and improvements on how we surface errors in the wallet; this work is tracked elsewhere.

**Comment by 100kdiamond** [comment]
Thank you!
