### ISSUE TITLE
GAS claim button in `Token Stats` for NEO is hard to find

### ISSUE THREAD

**Issue by AlleniCode** [aphtoken/aph-wallet-gui#33]
I install the mac wallet, but I cnnot find how to claim GAS.

**Comment by jsolman** [comment]
When logged in, on the dashboard tab, select the NEO asset in the `My Holdings` section. Then in the `Token Stats` section there is the the work `CLAIM` in purple. It is actually a button/link. We need to make it more obvious that it is click-able.

**Comment by jsolman** [comment]
Fixed in release 1.4.1
