### ISSUE TITLE
App does not scale properly on MacBook 12"

### ISSUE THREAD

**Issue by BiochemLouis** [aphtoken/aph-wallet-gui#36]
Great wallet and love the project, but just like Neon, the app does not properly scale for MacBook 12" (A1534).

The issue is found both in windowed and full screen.

The main problems are on the right side of the screen:
- dashboard: price and recent transactions
- assets: add token
- history: search bar (the only "problematic" one, the search button is off-screen)
- settings: import wallet

<img width="1280" alt="screen shot 2018-05-10 at 01 14 20" src="https://user-images.githubusercontent.com/26164870/39845767-ab641db4-53ef-11e8-88c3-d023ed981253.png">
<img width="1280" alt="screen shot 2018-05-10 at 01 04 37" src="https://user-images.githubusercontent.com/26164870/39845643-e036cb32-53ee-11e8-892b-fcc22d2e8aee.png">

**Comment by crishellco** [comment]
Hi Louis,

Try View > Zoom Out (⌘-) from the menu.

**Comment by RoseM2018** [comment]
Also the scaling problems on a laptop makes it difficult to use the send button for a coin.  There is no place to input number of tokens.
