### ISSUE TITLE
Should Ontology Token show in my balance?

### ISSUE THREAD

**Issue by the-louse** [aphtoken/aph-wallet-gui#45]
I can see the transaction credited by ONT balance in the recent transactions and on the neo block explorer, but the My holdings section is showing 0 ONT and when I try to send it says my Max is 0.

Thanks

**Comment by jsolman** [comment]
Please check the transaction history page again and report back if you seem to be experiencing any issue.

**Comment by jsolman** [comment]
We are not currently aware of any issues related to ONT balances.
