### ISSUE TITLE
Error while sending GAS with some Ledger devices

### ISSUE THREAD

**Issue by imolev** [aphtoken/aph-wallet-gui#53]
Good day, i am getting this error while sending GAS "Transaction failed: Ledger device: UNKNOWN_ERROR (0x6d08)".

NEON gives error like this: "Your transaction is too big for the ledger to sign".

OS: Windows 10
Ledger nano: neo app version 1.3.1

**Comment by jsolman** [comment]
I think we have seen this on Ledger BLU and need to look into it further. Are you using a Ledger Nano S or a Ledger BLU?

**Comment by jsolman** [comment]
Cannot reproduce. Please re-open if there are any more details.
